version: "3"

services:
  api:
    build:
      context: .
      dockerfile: dev.dockerfile
    ports:
      - 8000:8000
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:admin@database:5432/conchalabs_db
  database:
    image: postgres:14
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: conchalabs_db
